#include <iostream>
#include <Windows.h>

using namespace std;

void TextColor(int font, int background);

void main()
{
#pragma region 윗공백
	TextColor(0, 15);
	cout << "                                                                                " << endl;
	cout << "                                                                                " << endl;
	cout << "                                                                                " << endl;
	cout << "                                                                                " << endl;
	cout << "                                                                                " << endl;
	cout << "                                                                                " << endl;
#pragma endregion
#pragma region 머리 시작
	cout << "                                ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "     ";
	TextColor(0, 15);
	cout << "                                     " << endl;
	cout << "                             ";
	TextColor(0, 0);
	cout << "     ";
	TextColor(0, 15);
	cout << " ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 3);
	cout << "   ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 15);
	cout << "                                    " << endl;
	cout << "                           ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 11);
	cout << " ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 11);
	cout << " ";
	TextColor(0, 3);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 3);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "                                     " << endl;
	cout << "                          ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 11);
	cout << " ";
	TextColor(0, 3);
	cout << "      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 3);
	cout << " ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 15);
	cout << "                                     " << endl;
	cout << "                         ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 3);
	cout << "  ";
	TextColor(0, 11);
	cout << "  ";
	TextColor(0, 3);
	cout << "    ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 3);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 3);
	cout << " ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 15);
	cout << "                                      " << endl;
	cout << "                         ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 3);
	cout << " ";
	TextColor(0, 11);
	cout << "  ";
	TextColor(0, 3);
	cout << " ";
	TextColor(0, 11);
	cout << " ";
	TextColor(0, 3);
	cout << "  ";
	TextColor(0, 0);
	cout << "            ";
	TextColor(0, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 15);
	cout << "                            " << endl;
	TextColor(0, 15);
	cout << "                      ";
	TextColor(0, 0);
	cout << "     ";
	TextColor(0, 3);
	cout << " ";
	TextColor(0, 11);
	cout << "   ";
	TextColor(0, 3);
	cout << " ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 12);
	cout << " ";
	TextColor(0, 7);
	cout << "        ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 15);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "                          "<<endl;
	TextColor(0, 15);
	cout << "                    ";
	TextColor(0, 0);
	cout << "      ";
	TextColor(0, 3);
	cout << " ";
	TextColor(0, 11);
	cout << "    ";
	TextColor(0, 3);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 12);
	cout << "  ";
	TextColor(0, 7);
	cout << "           ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "                          " << endl;
	TextColor(0, 15);
	cout << "                 ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 12);
	cout << "     ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 3);
	cout << "    ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 12);
	cout << "            ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "   ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "                         "<<endl;
	TextColor(0, 15);
	cout << "               ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 12);
	cout << "  ";
	TextColor(0, 7);
	cout << "   ";
	TextColor(0, 12);
	cout << "  ";
	TextColor(0, 0);
	cout << "        ";
	TextColor(0, 12);
	cout << " ";
	TextColor(0, 0);
	cout << "              ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 14);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "                         " << endl;
	TextColor(0, 15);
	cout << "      ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 12);
	cout << "  ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 12);
	cout << "  ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 12);
	cout << "   ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 2);
	cout << "    ";
	TextColor(0, 0);
	cout << "     ";
	TextColor(0, 12);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 14);
	cout << "   ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "                         " << endl;
	TextColor(0, 15);
	cout << "      ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 14);
	cout << "   ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 12);
	cout << "  ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "     ";
	TextColor(0, 12);
	cout << "     ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 2);
	cout << "        ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 12);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "    ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "                         " << endl;
	TextColor(0, 15);
	cout << "      ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 14);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 12);
	cout << " ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 2);
	cout << "     ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 12);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << "  ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << "    ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "                        " << endl;
	TextColor(0, 15);
	cout << "      ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 14);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 15);
	cout << " ";
	TextColor(0, 12);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << "  ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 2);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "       ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << "         ";
	TextColor(0, 2);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "                        "<<endl;
	TextColor(0, 15);
	cout << "      ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 14);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 15);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << "  ";
	TextColor(0, 8);
	cout << "       ";
	TextColor(0, 2);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << "            ";
	TextColor(0, 2);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "   ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "                        "<<endl;
	TextColor(0, 15);
	cout << "      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 14);
	cout << " ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << "          ";
	TextColor(0, 2);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << "               ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << "   ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "                        " << endl;
	TextColor(0, 15);
	cout << "      ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 14);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 8);
	cout << "              ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 8);
	cout << "                  ";
	TextColor(0, 2);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "                        "<<endl;
	TextColor(0, 15);
	cout << "       ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 2);
	cout << "  ";
	TextColor(0, 8);
	cout << "                                     ";
	TextColor(0, 2);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 15);
	cout << "                        " << endl;
	TextColor(0, 15);
	cout << "       ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 2);
	cout << "  ";
	TextColor(0, 8);
	cout << "              ";
	TextColor(0, 0);
	cout << "               ";
	TextColor(0, 8);
	cout << "          ";
	TextColor(0, 2);
	cout << "   ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "                        "<<endl ;

	TextColor(0, 15);
	cout << "        ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 8);
	cout << "             ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << "               ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 8);
	cout << "         ";
	TextColor(0, 2);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "                       "<<endl;
	TextColor(0, 15);
	cout << "       ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 8);
	cout << "            ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << "                  ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "        ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "                       " << endl;
	TextColor(0, 15);
	cout << "      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << "         ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 7);
	cout << "                  ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 8);
	cout << "      ";
	TextColor(0, 2);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "       ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 15);
	cout << "           " << endl;
	TextColor(0, 15);
	cout << "      ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 2);
	cout << "  ";
	TextColor(0, 8);
	cout << "         ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << "                   ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 4);
	cout << "     ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "      ";
	TextColor(0, 2);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "     ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 15);
	cout << "          " << endl;
	TextColor(0, 15);
	cout << "     ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 8);
	cout << "        ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 7);
	cout << "                 ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 4);
	cout << "         ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 2);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "   ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << "   ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 15);
	cout << "         " << endl;
	TextColor(0, 15);
	cout << "     ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 2);
	cout << "  ";
	TextColor(0, 8);
	cout << "       ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 8);
	cout << "      ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "        ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 4);
	cout << "  ";
	TextColor(0, 12);
	cout << "    ";
	TextColor(0, 4);
	cout << "        ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << "      ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 15);
	cout << "        "<<endl;
	TextColor(0, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 8);
	cout << "       ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 4);
	cout << "     ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 4);
	cout << "  ";
	TextColor(0, 14);
	cout << "        ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 4);
	cout << "  ";
	TextColor(0, 12);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 4);
	cout << "     ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 2);
	cout << "      ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 15);
	cout << "        "<< endl;
	TextColor(0, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 8);
	cout << "       ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 4);
	cout << "    ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 12);
	cout << "    ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 14);
	cout << "         ";
	TextColor(0, 12);
	cout << "   ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 7);
	cout << "    ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 12);
	cout << " ";
	TextColor(0, 4);
	cout << "    ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 2);
	cout << "      ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0,15);
	cout << "         "<<endl;
	TextColor(0, 15);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 8);
	cout << "       ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 4);
	cout << "   ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 12);
	cout << "       ";
	TextColor(0, 14);
	cout << "          ";
	TextColor(0, 12);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 12);
	cout << "          ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 2);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 2);
	cout << "     ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "         "<<endl;
	TextColor(0, 15);
	cout << "   ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << "      ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 4);
	cout << "  ";
	TextColor(0, 12);
	cout << "  ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 12);
	cout << "  ";
	TextColor(0, 14);
	cout << "  ";
	TextColor(0, 7);
	cout << "     ";
	TextColor(0, 14);
	cout << "   ";
	TextColor(0, 12);
	cout << "              ";
	TextColor(0, 7);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 2);
	cout << "     ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "          "<<endl;
	TextColor(0, 15);
	cout << "   ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << "      ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 4);
	cout << "  ";
	TextColor(0, 12);
	cout << "  ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 12);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 12);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 14);
	cout << "   ";
	TextColor(0, 12);
	cout << "            ";
	TextColor(0, 14);
	cout << "   ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 2);
	cout << "     ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "          "<< endl;
	TextColor(0, 15);
	cout << "   ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << "      ";	
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 12);
	cout << "  ";
	TextColor(0, 14);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 12);
	cout << "       ";
	TextColor(0, 14);
	cout << "  ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 4);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "    ";
	TextColor(0, 12);
	cout << "         ";
	TextColor(0, 14);
	cout << "     ";
	TextColor(0, 7);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 2);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "          "<< endl;
	TextColor(0, 15);
	cout << "   ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "      ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 12);
	cout << "   ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 12);
	cout << "        ";
	TextColor(0, 14);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 14);
	cout << "       ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "             ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 4);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << "   ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "        "<<endl;
	TextColor(0, 15);
	cout << "   ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "     ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 12);
	cout << "            ";
	TextColor(0, 14);
	cout << "                                ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << "       ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "       "<<endl;
	TextColor(0, 15);
	cout << "   ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 14);
	cout << " ";
	TextColor(0, 12);
	cout << "          ";
	TextColor(0, 14);
	cout << "               ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 14);
	cout << "               ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 2);
	cout << "         ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "      "<<endl;
	TextColor(0, 15);
	cout << "   ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "  ";
	TextColor(0, 12);
	cout << "        ";
	TextColor(0, 14);
	cout << "                ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 14);
	cout << "                ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << "          ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 15);
	cout << "     "<<endl;
	TextColor(0, 15);
	cout << "   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "    ";
	TextColor(0, 12);
	cout << "  ";
	TextColor(0, 14);
	cout << "                 ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 14);
	cout << "                ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 2);
	cout << "             ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "     "<<endl;
	TextColor(0, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "                      ";
	TextColor(0, 12);
	cout << "  ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 14);
	cout << "                 ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 2);
	cout << "            ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 15);
	cout << "    "<<endl;
	TextColor(0, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "                ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << "    ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "                  ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "     ";
	TextColor(0, 2);
	cout << "             ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "    "<<endl;
	TextColor(0, 15);
	cout << "    ";
	TextColor(0, 14);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "                  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "                      ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << "             ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "    "<<endl;
	TextColor(0, 15);
	cout << "      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 14);
	cout << "                                         ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "     ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << "              ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 15);
	cout << "   "<<endl;
	TextColor(0, 15);
	cout << "       ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 14);
	cout << "                                     ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "     ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << "              ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 15);
	cout << "   " << endl;
	TextColor(0, 15);
	cout << "     ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 14);
	cout << "                                     ";
	TextColor(0, 7);
	cout << "   ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "          ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 2);
	cout << "         ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "    "<<endl;
	TextColor(0, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 14);
	cout << "                                    ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << "   ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "              ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << "       ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "   "<<endl;
	TextColor(0, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 14);
	cout << "                                   ";
	TextColor(0, 7);
	cout << "     ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "               ";
	TextColor(0, 2);
	cout << "      ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "    "<<endl;
	TextColor(0, 15);
	cout << "     ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 14);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "                            ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << "    ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "                  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 2);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "    "<<endl;
	TextColor(0, 15);
	cout << "       ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << "     ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "                       ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << "        ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "                 ";
	TextColor(0, 7);
	cout << "     ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "    "<<endl;
	TextColor(0, 15);
	cout << "      ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << "     ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "                   ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 4);
	cout << "  ";
	TextColor(0, 7);
	cout << "   ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << "        ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "                   ";
	TextColor(0, 7);
	cout << "    ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 15);
	cout << "   "<<endl;
	TextColor(0, 15);
	cout << "       ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << "      ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << "   ";
	TextColor(0, 14);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 14);
	cout << "         ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 7);
	cout << "            ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 8);
	cout << "                 ";
	TextColor(0, 7);
	cout << "    ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "    "<<endl;
	TextColor(0, 15);
	cout << "        ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << "                 ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << "      ";
	TextColor(0, 0);
	cout << "              ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "                   ";
	TextColor(0, 7);
	cout << "   ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "    "<<endl;
	TextColor(0, 15);
	cout << "        ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 7);
	cout << "          ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 7);
	cout << "   ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "         ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 4);
	cout << "        ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "                    ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 15);
	cout << "    "<<endl;
	TextColor(0, 15);
	cout << "          ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << "           ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 4);
	cout << "                  ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 8);
	cout << "                    ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 15);
	cout << "    "<<endl;
	TextColor(0, 15);
	cout << "             ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << "    ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 4);
	cout << "                        ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 8);
	cout << "                   ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "     "<<endl;
	TextColor(0, 15);
	cout << "               ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 4);
	cout << "                          ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "                   ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "      "<<endl;
	TextColor(0, 15);
	cout << "                 ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 4);
	cout << "                    ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 4);
	cout << "     ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "      "<<endl;
	TextColor(0, 15);
	cout << "                ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 4);
	cout << "                             ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 0);
	cout << "     ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 8);
	cout << "     ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 15);
	cout << "       "<<endl;
	TextColor(0, 15);
	cout << "              ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 4);
	cout << "                         ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 4);
	cout << "   ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 15);
	cout << "       "<<endl;
	TextColor(0, 15);
	cout << "            ";
	TextColor(0, 15);
	cout << "   ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 4);
	cout << "       ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 4);
	cout << "                 ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "     ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "     ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "        "<<endl;
	TextColor(0, 15);
	cout << "          ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 4);
	cout << "    ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 4);
	cout << "    ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 4);
	cout << "               ";
	TextColor(0, 8);
	cout << "      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "        ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "        ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "         "<<endl;
	TextColor(0, 15);
	cout << "           ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 4);
	cout << "   ";
	TextColor(0, 8);
	cout << "      ";
	TextColor(0, 4);
	cout << "   ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 4);
	cout << "      ";
	TextColor(0, 8);
	cout << "        ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "          ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "        ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 15);
	cout << "          "<<endl;
	TextColor(0, 15);
	cout << "            ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "        ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 8);
	cout << "         ";
	TextColor(0, 4);
	cout << " ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 4);
	cout << "     ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 15);
	cout << "             ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 15);
	cout << "             "<<endl;
	TextColor(0, 15);
	cout << "            ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "                             ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 15);
	cout << "                               "<<endl;
	TextColor(0, 15);
	cout << "            ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "     ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << "                  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 7);
	cout << "  ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 15);
	cout << "                                "<<endl;
	TextColor(0, 15);
	cout << "            ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "    ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 8);
	cout << "       ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "     ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 15);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "                                  "<<endl;
	TextColor(0, 15);
	cout << "             ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 15);
	cout << "   ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "   ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "     ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 8);
	cout << "  ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 15);
	cout << "                                      " << endl;
	TextColor(0, 15);
	cout << "                    ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 15);
	cout << "    ";
	TextColor(0, 0);
	cout << "    ";
	TextColor(0, 8);
	cout << " ";
	TextColor(0, 0);
	cout << " ";
	TextColor(0, 15);
	cout << "  ";
	TextColor(0, 7);
	cout << " ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "                                        " << endl;
	TextColor(0, 15);
	cout << "                      ";
	TextColor(0, 0);
	cout << "  ";
	TextColor(0, 15);
	cout << "        ";
	TextColor(0, 0);
	cout << "   ";
	TextColor(0, 15);
	cout << "                                     "<<endl;












}
void TextColor(int font, int background)
{
	int Color = font + background * 16;
	SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), Color);
}